### ISSUE TITLE
Bintray is deprecated

### ISSUE THREAD

**Issue by bakane6030** [kordlib/kordx.commands#36]
This extension is hosted on Bintray according to README.md, though it is impossible to fetch because JFrog deprecated Bintray. Is it possible to upload this extension to the Maven Central Repository?

**Comment by HopeBaron** [comment]
Hello there, 0.4.0-SNAPSHOT is available on maven central.
We are working on slash commands support before a stable release would be made.

**Comment by bakane6030** [comment]
Sure. Thanks! Be sure to update README after publishing the release.
